{
  "uid" : "9bf93c9fa9087ea6",
  "name" : "test_login_with_valid_email_and_invalid_password",
  "fullName" : "tests.test_login.TestLogin#test_login_with_valid_email_and_invalid_password",
  "historyId" : "a87129e8bc488f2c2b04474f72c047f1",
  "time" : {
    "start" : 1710960979302,
    "stop" : 1710960982708,
    "duration" : 3406
  },
  "status" : "failed",
  "statusMessage" : "AssertionError: assert False\n +  where False = <method-wrapper '__contains__' of str object at 0x000001F6D2575390>('Warning: No match for E-Mail Address and/or Password.')\n +    where <method-wrapper '__contains__' of str object at 0x000001F6D2575390> = 'Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.'.__contains__\n +      where 'Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.' = <bound method LoginPage.retrieve_warning_message of <pageobjectmodule.LoginPage.LoginPage object at 0x000001F6D257A2D0>>()\n +        where <bound method LoginPage.retrieve_warning_message of <pageobjectmodule.LoginPage.LoginPage object at 0x000001F6D257A2D0>> = <pageobjectmodule.LoginPage.LoginPage object at 0x000001F6D257A2D0>.retrieve_warning_message",
  "statusTrace" : "self = <tests.test_login.TestLogin object at 0x000001F6D253C350>\n\n    def test_login_with_valid_email_and_invalid_password(self):\n        home_page = HomePage(self.driver)\n        login_page = home_page.navigate_to_login_page()\n        login_page.login_to_application(\"purushotamtewari08@gmail.com\", \"Innovation@1991\")\n        time.sleep(2)\n        expected_warning_message = \"Warning: No match for E-Mail Address and/or Password.\"\n>       assert login_page.retrieve_warning_message().__contains__(expected_warning_message)\nE       AssertionError: assert False\nE        +  where False = <method-wrapper '__contains__' of str object at 0x000001F6D2575390>('Warning: No match for E-Mail Address and/or Password.')\nE        +    where <method-wrapper '__contains__' of str object at 0x000001F6D2575390> = 'Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.'.__contains__\nE        +      where 'Warning: Your account has exceeded allowed number of login attempts. Please try again in 1 hour.' = <bound method LoginPage.retrieve_warning_message of <pageobjectmodule.LoginPage.LoginPage object at 0x000001F6D257A2D0>>()\nE        +        where <bound method LoginPage.retrieve_warning_message of <pageobjectmodule.LoginPage.LoginPage object at 0x000001F6D257A2D0>> = <pageobjectmodule.LoginPage.LoginPage object at 0x000001F6D257A2D0>.retrieve_warning_message\n\ntests\\test_login.py:36: AssertionError",
  "flaky" : false,
  "beforeStages" : [ {
    "name" : "setup_and_teardown",
    "time" : {
      "start" : 1710960969990,
      "stop" : 1710960979300,
      "duration" : 9310
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false,
    "stepsCount" : 0
  }, {
    "name" : "log_on_failure",
    "time" : {
      "start" : 1710960979301,
      "stop" : 1710960979301,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false,
    "stepsCount" : 0
  } ],
  "afterStages" : [ {
    "name" : "setup_and_teardown::0",
    "time" : {
      "start" : 1710960983033,
      "stop" : 1710960985375,
      "duration" : 2342
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "hasContent" : false,
    "stepsCount" : 0
  }, {
    "name" : "log_on_failure::0",
    "time" : {
      "start" : 1710960982942,
      "stop" : 1710960983032,
      "duration" : 90
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "4bbe83cfa1bc8760",
      "name" : "failed_test",
      "source" : "4bbe83cfa1bc8760.png",
      "type" : "image/png",
      "size" : 122726
    } ],
    "parameters" : [ ],
    "attachmentsCount" : 1,
    "shouldDisplayMessage" : false,
    "hasContent" : true,
    "stepsCount" : 0
  } ],
  "labels" : [ {
    "name" : "tag",
    "value" : "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"
  }, {
    "name" : "parentSuite",
    "value" : "tests"
  }, {
    "name" : "suite",
    "value" : "test_login"
  }, {
    "name" : "subSuite",
    "value" : "TestLogin"
  }, {
    "name" : "host",
    "value" : "CTIVL0145"
  }, {
    "name" : "thread",
    "value" : "12044-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.test_login"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : true,
  "retry" : true,
  "extra" : {
    "categories" : [ ],
    "tags" : [ "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')" ]
  },
  "source" : "9bf93c9fa9087ea6.json",
  "parameterValues" : [ ]
}